### ISSUE TITLE
Setting filters on the client is not working

### ISSUE THREAD

**Issue by cherbst** [alethes/meteor-pages#101]
Setting filters on the client does not work at all. Not even in the provided Example:
https://github.com/alethes/meteor-pages/tree/master/examples/iron-router

**Comment by doubletaketech** [comment]
What proper syntax for adding a filter?  I'm trying to filter a collection by a Session.  The code below returns page numbers in pageNav, but no rows of data.
```
if Meteor.isClient
  @MeterPages = new Meteor.Pagination Meters,
        templateName: "meters"
        dataMargin: 5
        fastRender: true
        perPage: 20
        filters:
          projectId:
                Session.get('selectedProjectId')
        table:
          class: "table"
          fields: fields
          header: _.map fields, (f) -> f[0].toUpperCase() + f.slice 1 #Capitalize fields

```
